version: '3'
services:
  maplestory:
    build: .
    container_name: maplestory-server
    restart: unless-stopped
    depends_on:
      - db
    ports:
      # Login server
      - "8484:8484"
      # Channels
      # Scania
      - "7575:7575"
      # Bera
      - "7675:7675"
    volumes:
      # Config changes can be reloaded without rebuilding the image.
      # Still requires a redeployment as they're sourced on startup.
      - ./config.yaml:/opt/server/config.yaml
      - ./scripts:/opt/server/scripts
      - ./wz:/opt/server/wz
    environment:
      DB_HOST: "db" ## Remember if this is present it will OVERRIDE the host in the config.yaml, if you put here anything other than db, you'll need to change the config.yaml jdbc string to port 3307, and not port 3306
    networks:
      - db-network
    
  db:
    image: mysql:8.4.0
    container_name: maplestory-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "cosmic"
      MYSQL_USER: 'db_admin'
      MYSQL_PASSWORD: 'db_password'
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: no
      lower_case_table_names: 1
    volumes:
      - ./database/docker-db-data:/var/lib/mysql
      - ./database/sql:/docker-entrypoint-initdb.d
    networks:
      - db-network

  adminer:
    image: dockette/adminer:mysql
    container_name: adminer-container
    restart: unless-stopped
    ports:
      - "9090:80"  # Expose Adminer on port 9090
    depends_on:
      - db         # Ensure MySQL container is started before Adminer
    networks:
      - db-network
      
networks:
  db-network:
    driver: bridge